// The systemd env drop-in: the only file that arms mainnet, and the only writer
// of it.
//
// The mode is a boot-time property and this design keeps it that way. env() is
// cached for the process lifetime and nothing invalidates it, which is not a
// limitation to route around but the property the whole mainnet path rests on:
// the boot guard runs once, sodexChain()'s per-venue aidCache/symbolNameToInfo
// are only cleared by a fresh process, and submitApprovedOrder compares a stored
// orders.mode against env() precisely because env cannot move underneath it. So
// arming does not mutate a running process; it writes this file and restarts.
//
// systemd reads EnvironmentFile directives in order and the later one wins, so
// the unit lists:
//
//   EnvironmentFile=/root/sonar/.env.local
//   EnvironmentFile=-/root/sonar/.env.mode
//
// The "-" makes a missing file a non-error. That is what makes DISARMING equal
// DELETING: no file means the process boots on the .env.local baseline, which is
// testnet. The kill switch is `rm .env.mode && systemctl restart sonar`.
//
// Verified 2026-07-17 that this actually works: @next/env does NOT overwrite a
// key already present in process.env, so systemd's value survives Next's own
// .env.local loading. Probed against @next/env@16.2.4 with .env.local saying
// live-testnet and the process pre-set to live-mainnet: the pre-set value won,
// and .env.local-only keys still loaded. If a Next upgrade ever changes that,
// this design breaks silently and mainnet would never arm; re-run that probe.

import { writeFileSync, renameSync, unlinkSync, existsSync } from "node:fs";
import {
  VALUECHAIN_MAINNET_USDC,
  VALUECHAIN_MAINNET_RPC,
} from "@/lib/chain/valuechain";

export const DROPIN_PATH = "/root/sonar/.env.mode";

/**
 * The mainnet profile. Three variables, not one.
 *
 * Flipping SONAR_EXECUTION_MODE alone would boot into mainnet still holding the
 * testnet USDC and RPC from .env.local. Probed 2026-07-17: each USDC address is
 * dead code on the other chain, so that mismatch shows up as a zero balance
 * rather than an error, exactly when someone is checking whether real funds
 * landed. lib/utils/env.ts asserts all three by value at boot.
 *
 * Machine-generated with no interpolated input: the only free variable in the
 * whole flow is the mode enum, already narrowed by zod at the route boundary.
 */
export function renderDropin(): string {
  return [
    "# GENERATED by POST /api/admin/mode. Do not hand-edit.",
    "# Presence of this file ARMS live-mainnet on the next process start.",
    "# Disarm: rm /root/sonar/.env.mode && systemctl restart sonar",
    "SONAR_EXECUTION_MODE=live-mainnet",
    `VALUECHAIN_USDC_ADDRESS=${VALUECHAIN_MAINNET_USDC}`,
    `VALUECHAIN_RPC_URL=${VALUECHAIN_MAINNET_RPC}`,
    "",
  ].join("\n");
}

/** The env this drop-in would produce, for preflighting before it is written. */
export function dropinOverrides(): Record<string, string> {
  return {
    SONAR_EXECUTION_MODE: "live-mainnet",
    VALUECHAIN_USDC_ADDRESS: VALUECHAIN_MAINNET_USDC,
    VALUECHAIN_RPC_URL: VALUECHAIN_MAINNET_RPC,
  };
}

/**
 * Write via temp + rename. The rename is atomic within a filesystem, so systemd
 * can never read a half-written file: it sees the old drop-in or the new one,
 * never a torn one that parses into a mode without its margin asset.
 */
export function writeDropinAtomic(): void {
  const tmp = `${DROPIN_PATH}.tmp`;
  writeFileSync(tmp, renderDropin(), { mode: 0o600 });
  renameSync(tmp, DROPIN_PATH);
}

export function removeDropin(): void {
  if (existsSync(DROPIN_PATH)) unlinkSync(DROPIN_PATH);
}

export function dropinExists(): boolean {
  return existsSync(DROPIN_PATH);
}
